//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.10 at 10:03:40 AM EDT 
//


package opin.dictionary.dictDef;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sw complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sw">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cs.pitt.edu/mpqa/}entryBaseType">
 *       &lt;sequence>
 *         &lt;element name="entryDefinition" type="{http://www.cs.pitt.edu/mpqa/}entryDefinitionSwType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sw", propOrder = {
    "entryDefinition"
})
public class Sw
    extends EntryBaseType
{

    @XmlElement(required = true)
    protected EntryDefinitionSwType entryDefinition;

    /**
     * Gets the value of the entryDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link EntryDefinitionSwType }
     *     
     */
    public EntryDefinitionSwType getEntryDefinition() {
        return entryDefinition;
    }

    /**
     * Sets the value of the entryDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryDefinitionSwType }
     *     
     */
    public void setEntryDefinition(EntryDefinitionSwType value) {
        this.entryDefinition = value;
    }

}
