//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.10 at 10:03:40 AM EDT 
//


package opin.dictionary.dictDef;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entryDefinitionSwType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entryDefinitionSwType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="morphoSyntax" type="{http://www.cs.pitt.edu/mpqa/}morphoSyntaxType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entryDefinitionSwType", propOrder = {
    "morphoSyntax"
})
public class EntryDefinitionSwType {

    @XmlElement(required = true)
    protected MorphoSyntaxType morphoSyntax;

    /**
     * Gets the value of the morphoSyntax property.
     * 
     * @return
     *     possible object is
     *     {@link MorphoSyntaxType }
     *     
     */
    public MorphoSyntaxType getMorphoSyntax() {
        return morphoSyntax;
    }

    /**
     * Sets the value of the morphoSyntax property.
     * 
     * @param value
     *     allowed object is
     *     {@link MorphoSyntaxType }
     *     
     */
    public void setMorphoSyntax(MorphoSyntaxType value) {
        this.morphoSyntax = value;
    }

}
