//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.10 at 10:03:40 AM EDT 
//


package opin.dictionary.dictDef;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for majorClassType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="majorClassType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.cs.pitt.edu/mpqa/>majorClassTagType">
 *       &lt;attribute name="force" type="{http://www.cs.pitt.edu/mpqa/}forceType" default="positive" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "majorClassType", propOrder = {
    "value"
})
public class MajorClassType {

    @XmlValue
    protected MajorClassTagType value;
    @XmlAttribute
    protected ForceType force;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link MajorClassTagType }
     *     
     */
    public MajorClassTagType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link MajorClassTagType }
     *     
     */
    public void setValue(MajorClassTagType value) {
        this.value = value;
    }

    /**
     * Gets the value of the force property.
     * 
     * @return
     *     possible object is
     *     {@link ForceType }
     *     
     */
    public ForceType getForce() {
        if (force == null) {
            return ForceType.POSITIVE;
        } else {
            return force;
        }
    }

    /**
     * Sets the value of the force property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForceType }
     *     
     */
    public void setForce(ForceType value) {
        this.force = value;
    }

}
