//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.10 at 10:06:49 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cs.pitt.edu/mpqa/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package opin.dictionary.Merged;
