//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.10 at 10:06:49 AM EDT 
//


package opin.dictionary.Merged;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ruppenhofer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ruppenhofer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cs.pitt.edu/mpqa/}entryAttributesBaseType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subjective" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reliability" type="{http://www.cs.pitt.edu/mpqa/}reliabilityType" minOccurs="0"/>
 *         &lt;element name="confidence" type="{http://www.cs.pitt.edu/mpqa/}reliabilityType" minOccurs="0"/>
 *         &lt;element name="subType" type="{http://www.cs.pitt.edu/mpqa/}subType" minOccurs="0"/>
 *         &lt;element name="example" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="morphosyn" type="{http://www.cs.pitt.edu/mpqa/}morphosynType" minOccurs="0"/>
 *         &lt;element name="domain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sp_target" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sp_polarity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sp_intensity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sp_confidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sp2_target" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sp2_polarity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sp2_intensity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sp2_confidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fr_source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fr_target" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fr_intensity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fr_polarity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fr_confidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fr2_source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fr2_target" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fr2_intensity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fr2_polarity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fr2_confidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="patterntype" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastmodified" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruppenhofer", propOrder = {
    "name",
    "subjective",
    "origin",
    "reliability",
    "confidence",
    "subType",
    "example",
    "morphosyn",
    "domain",
    "spTarget",
    "spPolarity",
    "spIntensity",
    "spConfidence",
    "sp2Target",
    "sp2Polarity",
    "sp2Intensity",
    "sp2Confidence",
    "frSource",
    "frTarget",
    "frIntensity",
    "frPolarity",
    "frConfidence",
    "fr2Source",
    "fr2Target",
    "fr2Intensity",
    "fr2Polarity",
    "fr2Confidence",
    "regex",
    "patterntype",
    "lastmodified"
})
public class Ruppenhofer
    extends EntryAttributesBaseType
{

    @XmlElement(required = true)
    protected String name;
    protected boolean subjective;
    @XmlElement(required = true)
    protected String origin;
    protected ReliabilityType reliability;
    protected ReliabilityType confidence;
    protected SubType subType;
    protected String example;
    protected MorphosynType morphosyn;
    protected String domain;
    @XmlElement(name = "sp_target")
    protected String spTarget;
    @XmlElement(name = "sp_polarity")
    protected String spPolarity;
    @XmlElement(name = "sp_intensity")
    protected String spIntensity;
    @XmlElement(name = "sp_confidence")
    protected String spConfidence;
    @XmlElement(name = "sp2_target")
    protected String sp2Target;
    @XmlElement(name = "sp2_polarity")
    protected String sp2Polarity;
    @XmlElement(name = "sp2_intensity")
    protected String sp2Intensity;
    @XmlElement(name = "sp2_confidence")
    protected String sp2Confidence;
    @XmlElement(name = "fr_source")
    protected String frSource;
    @XmlElement(name = "fr_target")
    protected String frTarget;
    @XmlElement(name = "fr_intensity")
    protected String frIntensity;
    @XmlElement(name = "fr_polarity")
    protected String frPolarity;
    @XmlElement(name = "fr_confidence")
    protected String frConfidence;
    @XmlElement(name = "fr2_source")
    protected String fr2Source;
    @XmlElement(name = "fr2_target")
    protected String fr2Target;
    @XmlElement(name = "fr2_intensity")
    protected String fr2Intensity;
    @XmlElement(name = "fr2_polarity")
    protected String fr2Polarity;
    @XmlElement(name = "fr2_confidence")
    protected String fr2Confidence;
    protected String regex;
    protected String patterntype;
    protected XMLGregorianCalendar lastmodified;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the subjective property.
     * 
     */
    public boolean isSubjective() {
        return subjective;
    }

    /**
     * Sets the value of the subjective property.
     * 
     */
    public void setSubjective(boolean value) {
        this.subjective = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the reliability property.
     * 
     * @return
     *     possible object is
     *     {@link ReliabilityType }
     *     
     */
    public ReliabilityType getReliability() {
        return reliability;
    }

    /**
     * Sets the value of the reliability property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReliabilityType }
     *     
     */
    public void setReliability(ReliabilityType value) {
        this.reliability = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link ReliabilityType }
     *     
     */
    public ReliabilityType getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReliabilityType }
     *     
     */
    public void setConfidence(ReliabilityType value) {
        this.confidence = value;
    }

    /**
     * Gets the value of the subType property.
     * 
     * @return
     *     possible object is
     *     {@link SubType }
     *     
     */
    public SubType getSubType() {
        return subType;
    }

    /**
     * Sets the value of the subType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubType }
     *     
     */
    public void setSubType(SubType value) {
        this.subType = value;
    }

    /**
     * Gets the value of the example property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExample() {
        return example;
    }

    /**
     * Sets the value of the example property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExample(String value) {
        this.example = value;
    }

    /**
     * Gets the value of the morphosyn property.
     * 
     * @return
     *     possible object is
     *     {@link MorphosynType }
     *     
     */
    public MorphosynType getMorphosyn() {
        return morphosyn;
    }

    /**
     * Sets the value of the morphosyn property.
     * 
     * @param value
     *     allowed object is
     *     {@link MorphosynType }
     *     
     */
    public void setMorphosyn(MorphosynType value) {
        this.morphosyn = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomain(String value) {
        this.domain = value;
    }

    /**
     * Gets the value of the spTarget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpTarget() {
        return spTarget;
    }

    /**
     * Sets the value of the spTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpTarget(String value) {
        this.spTarget = value;
    }

    /**
     * Gets the value of the spPolarity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpPolarity() {
        return spPolarity;
    }

    /**
     * Sets the value of the spPolarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpPolarity(String value) {
        this.spPolarity = value;
    }

    /**
     * Gets the value of the spIntensity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpIntensity() {
        return spIntensity;
    }

    /**
     * Sets the value of the spIntensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpIntensity(String value) {
        this.spIntensity = value;
    }

    /**
     * Gets the value of the spConfidence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpConfidence() {
        return spConfidence;
    }

    /**
     * Sets the value of the spConfidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpConfidence(String value) {
        this.spConfidence = value;
    }

    /**
     * Gets the value of the sp2Target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSp2Target() {
        return sp2Target;
    }

    /**
     * Sets the value of the sp2Target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSp2Target(String value) {
        this.sp2Target = value;
    }

    /**
     * Gets the value of the sp2Polarity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSp2Polarity() {
        return sp2Polarity;
    }

    /**
     * Sets the value of the sp2Polarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSp2Polarity(String value) {
        this.sp2Polarity = value;
    }

    /**
     * Gets the value of the sp2Intensity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSp2Intensity() {
        return sp2Intensity;
    }

    /**
     * Sets the value of the sp2Intensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSp2Intensity(String value) {
        this.sp2Intensity = value;
    }

    /**
     * Gets the value of the sp2Confidence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSp2Confidence() {
        return sp2Confidence;
    }

    /**
     * Sets the value of the sp2Confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSp2Confidence(String value) {
        this.sp2Confidence = value;
    }

    /**
     * Gets the value of the frSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrSource() {
        return frSource;
    }

    /**
     * Sets the value of the frSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrSource(String value) {
        this.frSource = value;
    }

    /**
     * Gets the value of the frTarget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrTarget() {
        return frTarget;
    }

    /**
     * Sets the value of the frTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrTarget(String value) {
        this.frTarget = value;
    }

    /**
     * Gets the value of the frIntensity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrIntensity() {
        return frIntensity;
    }

    /**
     * Sets the value of the frIntensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrIntensity(String value) {
        this.frIntensity = value;
    }

    /**
     * Gets the value of the frPolarity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrPolarity() {
        return frPolarity;
    }

    /**
     * Sets the value of the frPolarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrPolarity(String value) {
        this.frPolarity = value;
    }

    /**
     * Gets the value of the frConfidence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrConfidence() {
        return frConfidence;
    }

    /**
     * Sets the value of the frConfidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrConfidence(String value) {
        this.frConfidence = value;
    }

    /**
     * Gets the value of the fr2Source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFr2Source() {
        return fr2Source;
    }

    /**
     * Sets the value of the fr2Source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFr2Source(String value) {
        this.fr2Source = value;
    }

    /**
     * Gets the value of the fr2Target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFr2Target() {
        return fr2Target;
    }

    /**
     * Sets the value of the fr2Target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFr2Target(String value) {
        this.fr2Target = value;
    }

    /**
     * Gets the value of the fr2Intensity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFr2Intensity() {
        return fr2Intensity;
    }

    /**
     * Sets the value of the fr2Intensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFr2Intensity(String value) {
        this.fr2Intensity = value;
    }

    /**
     * Gets the value of the fr2Polarity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFr2Polarity() {
        return fr2Polarity;
    }

    /**
     * Sets the value of the fr2Polarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFr2Polarity(String value) {
        this.fr2Polarity = value;
    }

    /**
     * Gets the value of the fr2Confidence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFr2Confidence() {
        return fr2Confidence;
    }

    /**
     * Sets the value of the fr2Confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFr2Confidence(String value) {
        this.fr2Confidence = value;
    }

    /**
     * Gets the value of the regex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegex() {
        return regex;
    }

    /**
     * Sets the value of the regex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegex(String value) {
        this.regex = value;
    }

    /**
     * Gets the value of the patterntype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatterntype() {
        return patterntype;
    }

    /**
     * Sets the value of the patterntype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatterntype(String value) {
        this.patterntype = value;
    }

    /**
     * Gets the value of the lastmodified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastmodified() {
        return lastmodified;
    }

    /**
     * Sets the value of the lastmodified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastmodified(XMLGregorianCalendar value) {
        this.lastmodified = value;
    }

}
