//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.10 at 10:09:30 AM EDT 
//


package opin.dictionary.MergedTff;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for tff complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tff">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cs.pitt.edu/mpqa/}entryAttributesBaseType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="origpats" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="origtypes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="polannsrc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="intensity" type="{http://www.cs.pitt.edu/mpqa/}intensityType" minOccurs="0"/>
 *         &lt;element name="othertypes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="polarplus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mpqapolarity" type="{http://www.cs.pitt.edu/mpqa/}polarityType" minOccurs="0"/>
 *         &lt;element name="polarity" type="{http://www.cs.pitt.edu/mpqa/}polaritySimpleType" minOccurs="0"/>
 *         &lt;element name="priorpolarity" type="{http://www.cs.pitt.edu/mpqa/}priorpolarityType" minOccurs="0"/>
 *         &lt;element name="highprec" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="RFE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MISS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="len" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastmodified" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tff", propOrder = {
    "name",
    "type",
    "origpats",
    "origtypes",
    "polannsrc",
    "intensity",
    "othertypes",
    "polarplus",
    "mpqapolarity",
    "polarity",
    "priorpolarity",
    "highprec",
    "rfe",
    "miss",
    "len",
    "regex",
    "lastmodified"
})
public class Tff
    extends EntryAttributesBaseType
{

    @XmlElement(required = true)
    protected String name;
    protected String type;
    protected String origpats;
    protected String origtypes;
    protected String polannsrc;
    protected IntensityType intensity;
    protected String othertypes;
    protected String polarplus;
    protected PolarityType mpqapolarity;
    protected PolaritySimpleType polarity;
    protected PriorpolarityType priorpolarity;
    protected Boolean highprec;
    @XmlElement(name = "RFE")
    protected String rfe;
    @XmlElement(name = "MISS")
    protected String miss;
    protected Integer len;
    protected String regex;
    protected XMLGregorianCalendar lastmodified;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the origpats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigpats() {
        return origpats;
    }

    /**
     * Sets the value of the origpats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigpats(String value) {
        this.origpats = value;
    }

    /**
     * Gets the value of the origtypes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigtypes() {
        return origtypes;
    }

    /**
     * Sets the value of the origtypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigtypes(String value) {
        this.origtypes = value;
    }

    /**
     * Gets the value of the polannsrc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolannsrc() {
        return polannsrc;
    }

    /**
     * Sets the value of the polannsrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolannsrc(String value) {
        this.polannsrc = value;
    }

    /**
     * Gets the value of the intensity property.
     * 
     * @return
     *     possible object is
     *     {@link IntensityType }
     *     
     */
    public IntensityType getIntensity() {
        return intensity;
    }

    /**
     * Sets the value of the intensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntensityType }
     *     
     */
    public void setIntensity(IntensityType value) {
        this.intensity = value;
    }

    /**
     * Gets the value of the othertypes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOthertypes() {
        return othertypes;
    }

    /**
     * Sets the value of the othertypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOthertypes(String value) {
        this.othertypes = value;
    }

    /**
     * Gets the value of the polarplus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolarplus() {
        return polarplus;
    }

    /**
     * Sets the value of the polarplus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolarplus(String value) {
        this.polarplus = value;
    }

    /**
     * Gets the value of the mpqapolarity property.
     * 
     * @return
     *     possible object is
     *     {@link PolarityType }
     *     
     */
    public PolarityType getMpqapolarity() {
        return mpqapolarity;
    }

    /**
     * Sets the value of the mpqapolarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolarityType }
     *     
     */
    public void setMpqapolarity(PolarityType value) {
        this.mpqapolarity = value;
    }

    /**
     * Gets the value of the polarity property.
     * 
     * @return
     *     possible object is
     *     {@link PolaritySimpleType }
     *     
     */
    public PolaritySimpleType getPolarity() {
        return polarity;
    }

    /**
     * Sets the value of the polarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolaritySimpleType }
     *     
     */
    public void setPolarity(PolaritySimpleType value) {
        this.polarity = value;
    }

    /**
     * Gets the value of the priorpolarity property.
     * 
     * @return
     *     possible object is
     *     {@link PriorpolarityType }
     *     
     */
    public PriorpolarityType getPriorpolarity() {
        return priorpolarity;
    }

    /**
     * Sets the value of the priorpolarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriorpolarityType }
     *     
     */
    public void setPriorpolarity(PriorpolarityType value) {
        this.priorpolarity = value;
    }

    /**
     * Gets the value of the highprec property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHighprec() {
        return highprec;
    }

    /**
     * Sets the value of the highprec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHighprec(Boolean value) {
        this.highprec = value;
    }

    /**
     * Gets the value of the rfe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRFE() {
        return rfe;
    }

    /**
     * Sets the value of the rfe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRFE(String value) {
        this.rfe = value;
    }

    /**
     * Gets the value of the miss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMISS() {
        return miss;
    }

    /**
     * Sets the value of the miss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMISS(String value) {
        this.miss = value;
    }

    /**
     * Gets the value of the len property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLen() {
        return len;
    }

    /**
     * Sets the value of the len property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLen(Integer value) {
        this.len = value;
    }

    /**
     * Gets the value of the regex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegex() {
        return regex;
    }

    /**
     * Sets the value of the regex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegex(String value) {
        this.regex = value;
    }

    /**
     * Gets the value of the lastmodified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastmodified() {
        return lastmodified;
    }

    /**
     * Sets the value of the lastmodified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastmodified(XMLGregorianCalendar value) {
        this.lastmodified = value;
    }

}
