//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 01:13:50 AM EDT 
//


package opin.dictionary.dictAttYaw;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for polarityTagType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="polarityTagType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="pos"/>
 *     &lt;enumeration value="neutral"/>
 *     &lt;enumeration value="neg"/>
 *     &lt;enumeration value="posneg"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum PolarityTagType {

    @XmlEnumValue("pos")
    POS("pos"),
    @XmlEnumValue("neutral")
    NEUTRAL("neutral"),
    @XmlEnumValue("neg")
    NEG("neg"),
    @XmlEnumValue("posneg")
    POSNEG("posneg");
    private final String value;

    PolarityTagType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PolarityTagType fromValue(String v) {
        for (PolarityTagType c: PolarityTagType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
