//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 01:13:50 AM EDT 
//


package opin.dictionary.dictAttYaw;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for subjectivityTagType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="subjectivityTagType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="subj"/>
 *     &lt;enumeration value="obj"/>
 *     &lt;enumeration value="both"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum SubjectivityTagType {

    @XmlEnumValue("subj")
    SUBJ("subj"),
    @XmlEnumValue("obj")
    OBJ("obj"),
    @XmlEnumValue("both")
    BOTH("both");
    private final String value;

    SubjectivityTagType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubjectivityTagType fromValue(String v) {
        for (SubjectivityTagType c: SubjectivityTagType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
