//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.10 at 10:05:25 AM EDT 
//


package opin.dictionary.dictAtt;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dictAttributes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dictAttributes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Lexicon }
     * 
     */
    public Lexicon createLexicon() {
        return new Lexicon();
    }

    /**
     * Create an instance of {@link Ruppenhofer }
     * 
     */
    public Ruppenhofer createRuppenhofer() {
        return new Ruppenhofer();
    }

    /**
     * Create an instance of {@link LexiconMetadataType }
     * 
     */
    public LexiconMetadataType createLexiconMetadataType() {
        return new LexiconMetadataType();
    }

}
