//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.10 at 10:05:25 AM EDT 
//


package opin.dictionary.dictAtt;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for morphosynType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="morphosynType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="vp"/>
 *     &lt;enumeration value="np"/>
 *     &lt;enumeration value="pp"/>
 *     &lt;enumeration value="cl"/>
 *     &lt;enumeration value="j"/>
 *     &lt;enumeration value="r"/>
 *     &lt;enumeration value="v"/>
 *     &lt;enumeration value="n"/>
 *     &lt;enumeration value="u"/>
 *     &lt;enumeration value="a"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum MorphosynType {

    @XmlEnumValue("vp")
    VP("vp"),
    @XmlEnumValue("np")
    NP("np"),
    @XmlEnumValue("pp")
    PP("pp"),
    @XmlEnumValue("cl")
    CL("cl"),
    @XmlEnumValue("j")
    J("j"),
    @XmlEnumValue("r")
    R("r"),
    @XmlEnumValue("v")
    V("v"),
    @XmlEnumValue("n")
    N("n"),
    @XmlEnumValue("u")
    U("u"),
    @XmlEnumValue("a")
    A("a");
    private final String value;

    MorphosynType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MorphosynType fromValue(String v) {
        for (MorphosynType c: MorphosynType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
