//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.10 at 10:06:49 AM EDT 
//


package opin.dictionary.Merged;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wordNetSense complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wordNetSense">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cs.pitt.edu/mpqa/}senseBaseType">
 *       &lt;attribute name="mC" use="required" type="{http://www.cs.pitt.edu/mpqa/}majorClassTagType" />
 *       &lt;attribute name="senseNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wordNetSense")
public class WordNetSense
    extends SenseBaseType
{

    @XmlAttribute(name = "mC", required = true)
    protected MajorClassTagType mc;
    @XmlAttribute(required = true)
    protected int senseNumber;
    @XmlAttribute(required = true)
    protected String version;

    /**
     * Gets the value of the mc property.
     * 
     * @return
     *     possible object is
     *     {@link MajorClassTagType }
     *     
     */
    public MajorClassTagType getMC() {
        return mc;
    }

    /**
     * Sets the value of the mc property.
     * 
     * @param value
     *     allowed object is
     *     {@link MajorClassTagType }
     *     
     */
    public void setMC(MajorClassTagType value) {
        this.mc = value;
    }

    /**
     * Gets the value of the senseNumber property.
     * 
     */
    public int getSenseNumber() {
        return senseNumber;
    }

    /**
     * Sets the value of the senseNumber property.
     * 
     */
    public void setSenseNumber(int value) {
        this.senseNumber = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
