//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.30 at 01:20:57 PM EDT 
//


package opin.dictionary.dictDefSimple;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dictSimple package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dictSimple
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link EntryAttributesType }
     * 
     */
    public EntryAttributesType createEntryAttributesType() {
        return new EntryAttributesType();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link ItemRelationType }
     * 
     */
    public ItemRelationType createItemRelationType() {
        return new ItemRelationType();
    }

    /**
     * Create an instance of {@link DepType }
     * 
     */
    public DepType createDepType() {
        return new DepType();
    }

    /**
     * Create an instance of {@link EntryDefinitionType }
     * 
     */
    public EntryDefinitionType createEntryDefinitionType() {
        return new EntryDefinitionType();
    }

    /**
     * Create an instance of {@link ItemMorphoSyntaxType }
     * 
     */
    public ItemMorphoSyntaxType createItemMorphoSyntaxType() {
        return new ItemMorphoSyntaxType();
    }

    /**
     * Create an instance of {@link PosType }
     * 
     */
    public PosType createPosType() {
        return new PosType();
    }

    /**
     * Create an instance of {@link Lexicon }
     * 
     */
    public Lexicon createLexicon() {
        return new Lexicon();
    }

}
