//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.30 at 01:20:57 PM EDT 
//


package opin.dictionary.dictDefSimple;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for itemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="itemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="itemMorphoSyntax" type="{}itemMorphoSyntaxType"/>
 *         &lt;element name="itemRelation" type="{}itemRelationType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemType", propOrder = {

})
public class ItemType {

    @XmlElement(required = true)
    protected ItemMorphoSyntaxType itemMorphoSyntax;
    protected ItemRelationType itemRelation;
    @XmlAttribute(required = true)
    protected BigInteger index;

    /**
     * Gets the value of the itemMorphoSyntax property.
     * 
     * @return
     *     possible object is
     *     {@link ItemMorphoSyntaxType }
     *     
     */
    public ItemMorphoSyntaxType getItemMorphoSyntax() {
        return itemMorphoSyntax;
    }

    /**
     * Sets the value of the itemMorphoSyntax property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemMorphoSyntaxType }
     *     
     */
    public void setItemMorphoSyntax(ItemMorphoSyntaxType value) {
        this.itemMorphoSyntax = value;
    }

    /**
     * Gets the value of the itemRelation property.
     * 
     * @return
     *     possible object is
     *     {@link ItemRelationType }
     *     
     */
    public ItemRelationType getItemRelation() {
        return itemRelation;
    }

    /**
     * Sets the value of the itemRelation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemRelationType }
     *     
     */
    public void setItemRelation(ItemRelationType value) {
        this.itemRelation = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndex(BigInteger value) {
        this.index = value;
    }

}
