//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.30 at 01:20:57 PM EDT 
//


package opin.dictionary.dictDefSimple;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for metadataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="metadataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="tokenizer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="posTagger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lemmatizer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dependencyParser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metadataType", propOrder = {

})
public class MetadataType {

    protected String tokenizer;
    protected String posTagger;
    protected String lemmatizer;
    protected String dependencyParser;

    /**
     * Gets the value of the tokenizer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenizer() {
        return tokenizer;
    }

    /**
     * Sets the value of the tokenizer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenizer(String value) {
        this.tokenizer = value;
    }

    /**
     * Gets the value of the posTagger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosTagger() {
        return posTagger;
    }

    /**
     * Sets the value of the posTagger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosTagger(String value) {
        this.posTagger = value;
    }

    /**
     * Gets the value of the lemmatizer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLemmatizer() {
        return lemmatizer;
    }

    /**
     * Sets the value of the lemmatizer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLemmatizer(String value) {
        this.lemmatizer = value;
    }

    /**
     * Gets the value of the dependencyParser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDependencyParser() {
        return dependencyParser;
    }

    /**
     * Sets the value of the dependencyParser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDependencyParser(String value) {
        this.dependencyParser = value;
    }

}
