//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.24 at 01:13:50 AM EDT 
//


package opin.dictionary.dictAttYaw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for yaw complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="yaw">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cs.pitt.edu/mpqa/}entryAttributesBaseType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subjectivityTag" type="{http://www.cs.pitt.edu/mpqa/}subjectivityTagType" minOccurs="0"/>
 *         &lt;element name="polarityTag" type="{http://www.cs.pitt.edu/mpqa/}polarityTagType" minOccurs="0"/>
 *         &lt;element name="lastmodified" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "yaw", propOrder = {
    "name",
    "subjectivityTag",
    "polarityTag",
    "lastmodified"
})
public class Yaw
    extends EntryAttributesBaseType
{

    @XmlElement(required = true)
    protected String name;
    protected SubjectivityTagType subjectivityTag;
    protected PolarityTagType polarityTag;
    protected XMLGregorianCalendar lastmodified;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the subjectivityTag property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectivityTagType }
     *     
     */
    public SubjectivityTagType getSubjectivityTag() {
        return subjectivityTag;
    }

    /**
     * Sets the value of the subjectivityTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectivityTagType }
     *     
     */
    public void setSubjectivityTag(SubjectivityTagType value) {
        this.subjectivityTag = value;
    }

    /**
     * Gets the value of the polarityTag property.
     * 
     * @return
     *     possible object is
     *     {@link PolarityTagType }
     *     
     */
    public PolarityTagType getPolarityTag() {
        return polarityTag;
    }

    /**
     * Sets the value of the polarityTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolarityTagType }
     *     
     */
    public void setPolarityTag(PolarityTagType value) {
        this.polarityTag = value;
    }

    /**
     * Gets the value of the lastmodified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastmodified() {
        return lastmodified;
    }

    /**
     * Sets the value of the lastmodified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastmodified(XMLGregorianCalendar value) {
        this.lastmodified = value;
    }

}
